extends: 
  - airbnb-base
  - prettier
plugins:
  - prettier
rules:
  prettier/prettier: [error]
  import/prefer-default-export: 0
  no-unused-expressions: 0
  no-restricted-syntax: 0
  no-nested-ternary: 0
parserOptions:
  ecmaVersion: 2022
  sourceType: module
  ecmaFeatures:
    modules: true

